const KidsproductsData = [
  {
    id: 1,
    name: "Cartoon Printed T-Shirt",
    brand: "KidsFun",
    category: "T-Shirts",
    mainImage: "https://th.bing.com/th/id/OIP.0pQW11BT7ANbfQDzggg3lwHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://th.bing.com/th/id/OIP.0pQW11BT7ANbfQDzggg3lwHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      "https://www.teacollection.com/mas_assets/cache/image/1/0/1/a/500x-1055442.Jpg ",
      "https://www.coqenpate.com/4013-thickbox_default/lion-t-shirt.jpg ",
    ],
    originalPrice: 599,
    discountedPrice: 419,
    discountPercentage: 30,
    size: ["2-3 Years", "4-5 Years", "6-7 Years", "8-9 Years"],
    sizes: [
      { value: "2-3 Years", label: "2-3 Years" },
      { value: "4-5 Years", label: "4-5 Years" },
      { value: "6-7 Years", label: "6-7 Years" },
      { value: "8-9 Years", label: "8-9 Years" },
    ],
    color: "Blue",
    materialComposition: "100% Cotton",
    variant: "Dinosaur Print",
    rating: 4.5,
    reviewsCount: 120,
    boughtInPastMonth: 80,
    newArrival: true,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Kids Fashion Hub",
    openBoxEligible: false,
    emiStartsAt: 140,
    protectPromiseFee: 20,
    offers: [
      {
        type: "Bank Offer",
        description: "10% off on ICICI Bank Cards",
      },
      {
        type: "Combo Offer",
        description: "Buy 2 get 10% off",
      },
    ],
  },
  {
    id: 2,
    name: "Denim Jeans for Boys",
    brand: "LittleBoss",
    category: "Bottomwear",
    mainImage: "https://5.imimg.com/data5/SELLER/Default/2024/3/396128618/UH/NG/TS/214558295/kajal-1000x1000.jpg",
    thumbnailImages: [
      " https://5.imimg.com/data5/SELLER/Default/2024/3/396128618/UH/NG/TS/214558295/kajal-1000x1000.jpg",
      "https://th.bing.com/th/id/OIP.JsvhVGgzbxIUqEiKgcKwxQHaIq?w=850&h=995&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      "https://5.imimg.com/data5/PB/SF/DS/ANDROID-8962968/product-jpeg-500x500.jpg",
    ],
    originalPrice: 899,
    discountedPrice: 629,
    discountPercentage: 30,
    size: ["3-4 Years", "5-6 Years", "7-8 Years"],
    sizes: [
      { value: "3-4 Years", label: "3-4 Years" },
      { value: "5-6 Years", label: "5-6 Years" },
      { value: "7-8 Years", label: "7-8 Years" },
    ],
    color: "Dark Blue",
    materialComposition: "98% Cotton, 2% Spandex",
    variant: "Regular Fit",
    rating: 4.3,
    reviewsCount: 95,
    boughtInPastMonth: 60,
    newArrival: false,
    deliveryDate: "2025-06-28",
    deliveryCharge: "₹40",
    seller: "Denim Kids",
    openBoxEligible: true,
    emiStartsAt: 210,
    protectPromiseFee: 15,
    offers: [
      {
        type: "App Exclusive",
        description: "Extra 5% off on App",
      },
    ],
  },
  {
    id: 3,
    name: "Floral Dress for Girls",
    brand: "PrincessStyle",
    category: "Dresses",
    mainImage: "https://th.bing.com/th/id/OIP.A6uswzazYwh33B89LCX4fgHaJx?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      " https://th.bing.com/th/id/OIP.A6uswzazYwh33B89LCX4fgHaJx?rs=1&pid=ImgDetMain&cb=idpwebpc2",
      "https://i.pinimg.com/736x/e9/19/1e/e9191e341311c621e65a1027caca9fca.jpg ",
      "https://th.bing.com/th/id/OIP.uKS0jlF1STLxBfDMoiCrtAAAAA?w=474&h=474&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
    ],
    originalPrice: 1299,
    discountedPrice: 909,
    discountPercentage: 30,
    size: ["2-3 Years", "4-5 Years", "6-7 Years"],
    sizes: [
      { value: "2-3 Years", label: "2-3 Years" },
      { value: "4-5 Years", label: "4-5 Years" },
      { value: "6-7 Years", label: "6-7 Years" },
    ],
    color: "Pink",
    materialComposition: "Cotton Blend",
    variant: "Party Wear",
    rating: 4.7,
    reviewsCount: 150,
    boughtInPastMonth: 90,
    newArrival: true,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Girls Fashion",
    openBoxEligible: false,
    emiStartsAt: 303,
    protectPromiseFee: 25,
    offers: [
      {
        type: "Festival Offer",
        description: "Flat ₹200 off",
      },
    ],
  },
  {
    id: 4,
    name: "Sports Shoes for Kids",
    brand: "ActiveKids",
    category: "Footwear",
    mainImage: "https://i5.walmartimages.com/asr/252a28e9-126a-43ac-b59c-2decfe1b2c7c.d805961b1e3737dbee1f4b7cbed1e01e.jpeg",
    thumbnailImages: [
      "https://i5.walmartimages.com/asr/252a28e9-126a-43ac-b59c-2decfe1b2c7c.d805961b1e3737dbee1f4b7cbed1e01e.jpeg ",
      "https://th.bing.com/th/id/OIP.ZR-ZIK6DCWwQqAY5JAxbCwHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      " https://i5.walmartimages.com/seo/Breathable-Mesh-Boys-Sneakers-Kids-Sports-Shoes-Quality-Athletic-Footwear_d46b268d-230d-4a79-8531-d0aef02349be.27716fbac163d3b15aa7538f829d1968.jpeg",
    ],
    originalPrice: 1499,
    discountedPrice: 1049,
    discountPercentage: 30,
    size: ["UK 10", "UK 11", "UK 12", "UK 13"],
    sizes: [
      { value: "UK 10", label: "UK 10" },
      { value: "UK 11", label: "UK 11" },
      { value: "UK 12", label: "UK 12" },
      { value: "UK 13", label: "UK 13" },
    ],
    color: "Black & Red",
    materialComposition: "Mesh & Rubber",
    variant: "Running Shoes",
    rating: 4.6,
    reviewsCount: 180,
    boughtInPastMonth: 120,
    newArrival: false,
    deliveryDate: "2025-06-29",
    deliveryCharge: "Free",
    seller: "Kids Footwear",
    openBoxEligible: true,
    emiStartsAt: 350,
    protectPromiseFee: 30,
    offers: [
      {
        type: "Sports Deal",
        description: "Free socks with purchase",
      },
    ],
  },
  {
    id: 5,
    name: "Cotton Pajama Set",
    brand: "CozyKids",
    category: "Sleepwear",
    mainImage: "https://th.bing.com/th/id/OIP.DyNiRsFsqZz71g80eLaVqAAAAA?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://th.bing.com/th/id/OIP.DyNiRsFsqZz71g80eLaVqAAAAA?rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      " https://th.bing.com/th/id/OIP.LWr3VYisHfr68WvU-7fYWwHaHa?w=600&h=600&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      "https://cdn.shopify.com/s/files/1/0276/4416/6186/files/2130834113797_500x500.jpg?v=1684424879 ",
    ],
    originalPrice: 799,
    discountedPrice: 559,
    discountPercentage: 30,
    size: ["1-2 Years", "3-4 Years", "5-6 Years"],
    sizes: [
      { value: "1-2 Years", label: "1-2 Years" },
      { value: "3-4 Years", label: "3-4 Years" },
      { value: "5-6 Years", label: "5-6 Years" },
    ],
    color: "Light Blue",
    materialComposition: "100% Cotton",
    variant: "Dinosaur Print",
    rating: 4.4,
    reviewsCount: 85,
    boughtInPastMonth: 50,
    newArrival: false,
    deliveryDate: "2025-06-28",
    deliveryCharge: "₹30",
    seller: "Sleep Comfort",
    openBoxEligible: false,
    emiStartsAt: 186,
    protectPromiseFee: 10,
    offers: [
      {
        type: "Combo Offer",
        description: "Buy 2 sets get 15% off",
      },
    ],
  },
  {
    id: 6,
    name: "Winter Jacket for Kids",
    brand: "WarmKids",
    category: "Winter Wear",
    mainImage: "https://th.bing.com/th/id/R.d4e7591174767fcfcaa47834b6df319c?rik=VAEXFt2II%2fmK0A&riu=http%3a%2f%2fi979.photobucket.com%2falbums%2fae277%2fcoolmomphotos%2fJ-Crew-puffer-winter-jacket_zpszfnasa3e.jpeg&ehk=wFjuoGhuUoA1jEDsmGUjRj6siBJYa%2fB2xhVg1nPvxc8%3d&risl=&pid=ImgRaw&r=0",
    thumbnailImages: [
      " https://th.bing.com/th/id/R.d4e7591174767fcfcaa47834b6df319c?rik=VAEXFt2II%2fmK0A&riu=http%3a%2f%2fi979.photobucket.com%2falbums%2fae277%2fcoolmomphotos%2fJ-Crew-puffer-winter-jacket_zpszfnasa3e.jpeg&ehk=wFjuoGhuUoA1jEDsmGUjRj6siBJYa%2fB2xhVg1nPvxc8%3d&risl=&pid=ImgRaw&r=0",
      "https://th.bing.com/th/id/OIP.uummig_LdOGQ_Ck_-06leAHaHa?w=800&h=800&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      " https://th.bing.com/th/id/OIP.bD8WaVRhBoh3loy1E7MzkAHaJh?w=1920&h=2467&rs=1&pid=ImgDetMain&cb=idpwebpc2",
    ],
    originalPrice: 1999,
    discountedPrice: 1399,
    discountPercentage: 30,
    size: ["3-4 Years", "5-6 Years", "7-8 Years"],
    sizes: [
      { value: "3-4 Years", label: "3-4 Years" },
      { value: "5-6 Years", label: "5-6 Years" },
      { value: "7-8 Years", label: "7-8 Years" },
    ],
    color: "Red",
    materialComposition: "Polyester Fill",
    variant: "Hooded",
    rating: 4.5,
    reviewsCount: 110,
    boughtInPastMonth: 70,
    newArrival: true,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Winter Essentials",
    openBoxEligible: false,
    emiStartsAt: 466,
    protectPromiseFee: 35,
    offers: [
      {
        type: "Winter Special",
        description: "Free beanie with purchase",
      },
    ],
  },
  {
    id: 7,
    name: "School Backpack",
    brand: "SchoolMate",
    category: "Accessories",
    mainImage: "https://d26olvxuieoyaa.cloudfront.net/catalog/product/cache/1/small_image/1000x1000/9df78eab33525d08d6e5fb8d27136e95/9/7/8887736042137_b1.jpg",
    thumbnailImages: [
      "https://d26olvxuieoyaa.cloudfront.net/catalog/product/cache/1/small_image/1000x1000/9df78eab33525d08d6e5fb8d27136e95/9/7/8887736042137_b1.jpg ",
      " https://5.imimg.com/data5/SELLER/Default/2022/1/MC/MX/TV/31696729/dsc-0159-1000x1000.JPG",
      " https://th.bing.com/th/id/OIP.9wCEssAxOoHyitvjUFkpXQHaHa?w=500&h=500&rs=1&pid=ImgDetMain&cb=idpwebpc2",
    ],
    originalPrice: 899,
    discountedPrice: 629,
    discountPercentage: 30,
    size: ["Small", "Medium"],
    sizes: [
      { value: "Small", label: "Small" },
      { value: "Medium", label: "Medium" },
    ],
    color: "Blue",
    materialComposition: "Polyester",
    variant: "With Lunch Box",
    rating: 4.6,
    reviewsCount: 200,
    boughtInPastMonth: 150,
    newArrival: false,
    deliveryDate: "2025-06-29",
    deliveryCharge: "Free",
    seller: "School Essentials",
    openBoxEligible: true,
    emiStartsAt: 210,
    protectPromiseFee: 20,
    offers: [
      {
        type: "Back to School",
        description: "15% off on all school items",
      },
    ],
  },
  {
    id: 8,
    name: "Cotton Romper for Babies",
    brand: "BabySoft",
    category: "Baby Clothes",
    mainImage: "https://i.pinimg.com/736x/4c/4a/7c/4c4a7c05f510c432dc562c08eb21b707.jpg",
    thumbnailImages: [
      "https://i.pinimg.com/736x/4c/4a/7c/4c4a7c05f510c432dc562c08eb21b707.jpg ",
      "https://th.bing.com/th/id/OIP.IbEzg7V5FtsJ0WsDnO7qSAHaHa?w=600&h=600&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      " https://i.etsystatic.com/iap/9bce02/5788043623/iap_600x600.5788043623_9ffphoc8.jpg?version=0",
    ],
    originalPrice: 499,
    discountedPrice: 349,
    discountPercentage: 30,
    size: ["0-6 Months", "6-12 Months"],
    sizes: [
      { value: "0-6 Months", label: "0-6 Months" },
      { value: "6-12 Months", label: "6-12 Months" },
    ],
    color: "Yellow",
    materialComposition: "100% Organic Cotton",
    variant: "Animal Print",
    rating: 4.8,
    reviewsCount: 180,
    boughtInPastMonth: 120,
    newArrival: false,
    deliveryDate: "2025-06-28",
    deliveryCharge: "Free",
    seller: "Baby Comfort",
    openBoxEligible: false,
    emiStartsAt: 116,
    protectPromiseFee: 10,
    offers: [
      {
        type: "Baby Care",
        description: "Buy 3 get 1 free",
      },
    ],
  },
  {
    id: 9,
    name: "Kids Sunglasses",
    brand: "SunnyKids",
    category: "Accessories",
    mainImage: "https://th.bing.com/th/id/OIP.GiYO7hQP-fNLkm5ZlGbtIwAAAA?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://th.bing.com/th/id/OIP.GiYO7hQP-fNLkm5ZlGbtIwAAAA?rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      "https://th.bing.com/th/id/OIP.y1y9pgLYrIo3feROG_fRwAHaJ4?w=2304&h=3072&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      " https://i.pinimg.com/736x/47/e3/8c/47e38c85e52d6084b15ab34e7570b039.jpg",
    ],
    originalPrice: 399,
    discountedPrice: 279,
    discountPercentage: 30,
    size: ["One Size"],
    sizes: [{ value: "One Size", label: "One Size" }],
    color: "Blue",
    materialComposition: "Plastic",
    variant: "UV Protection",
    rating: 4.2,
    reviewsCount: 75,
    boughtInPastMonth: 50,
    newArrival: true,
    deliveryDate: "2025-06-27",
    deliveryCharge: "₹30",
    seller: "Eye Protection",
    openBoxEligible: false,
    emiStartsAt: 93,
    protectPromiseFee: 5,
    offers: [
      {
        type: "Summer Special",
        description: "Buy 2 get 10% off",
      },
    ],
  },
  {
    id: 10,
    name: "Kids Raincoat",
    brand: "RainyDays",
    category: "Outerwear",
    mainImage: "https://www.fringoo.co.uk/cdn/shop/products/yellow-kids-raincoat-name-yellow.jpg?v=1663846464",
    thumbnailImages: [
      "https://www.fringoo.co.uk/cdn/shop/products/yellow-kids-raincoat-name-yellow.jpg?v=1663846464 ",
      "https://th.bing.com/th/id/OIP.jkLCnAnLypi6rr1YKwDXpQHaHa?w=1002&h=1002&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      "https://th.bing.com/th/id/OIP.otv1xA17J23p_pKjL9-3EAHaHa?w=1002&h=1002&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
    ],
    originalPrice: 1299,
    discountedPrice: 909,
    discountPercentage: 30,
    size: ["3-4 Years", "5-6 Years", "7-8 Years"],
    sizes: [
      { value: "3-4 Years", label: "3-4 Years" },
      { value: "5-6 Years", label: "5-6 Years" },
      { value: "7-8 Years", label: "7-8 Years" },
    ],
    color: "Yellow",
    materialComposition: "Waterproof Polyester",
    variant: "With Hood",
    rating: 4.5,
    reviewsCount: 65,
    boughtInPastMonth: 40,
    newArrival: false,
    deliveryDate: "2025-06-29",
    deliveryCharge: "Free",
    seller: "Rain Gear",
    openBoxEligible: false,
    emiStartsAt: 303,
    protectPromiseFee: 25,
    offers: [
      {
        type: "Monsoon Offer",
        description: "Free umbrella with purchase",
      },
    ],
  },
  {
    id: 11,      
    name: "Kids Sneakers",
    brand: "TinySteps",
    category: "Footwear",
    mainImage: "https://th.bing.com/th/id/OIP.9FYUHv_nU37MJ41jvjoT9gHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://th.bing.com/th/id/OIP.9FYUHv_nU37MJ41jvjoT9gHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      " https://th.bing.com/th/id/OIP.ZqINd2VQyKytdJUjTYo2uQHaHa?w=800&h=800&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      "https://th.bing.com/th/id/OIP.jyWJlJ-X4w-ODEGBEc3aLQHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
    ],
    originalPrice: 1599,
    discountedPrice: 1119,
    discountPercentage: 30,
    size: ["UK 1", "UK 2", "UK 3"],
    sizes: [
      { value: "UK 1", label: "UK 1" },
      { value: "UK 2", label: "UK 2" },
      { value: "UK 3", label: "UK 3" },
    ],
    color: "White",
    materialComposition: "Leather",
    variant: "Casual Shoes",
    rating: 4.8,
    reviewsCount: 200,
    boughtInPastMonth: 150,
    newArrival: true,
    deliveryDate: "2025-06-30",
    deliveryCharge: "Free",
    seller: "Sneaker World",
    openBoxEligible: true,
    emiStartsAt: 373,
    protectPromiseFee: 30,
    offers: [
      {
        type: "Seasonal Discount",
        description: "Buy 1 get 15% off on second pair",
      },
    ],
  },
  {
    id: 12,
    name: "Kids Hat",
    brand: "SunnyCaps",
    category: "Accessories",
    mainImage: "https://th.bing.com/th/id/OIP.oh5DQEnY8UmsnuX682t9swHaE8?o=7rm=3&rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://th.bing.com/th/id/OIP.oh5DQEnY8UmsnuX682t9swHaE8?o=7rm=3&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      "https://th.bing.com/th/id/OIP.bSOzGDlB9LePqEgVxBKZewHaE8?w=5184&h=3456&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      " https://freshairclothing.com/wp-content/uploads/2016/03/BlackGreenTreeOL.jpg",
    ],
    originalPrice: 499,
    discountedPrice: 349,
    discountPercentage: 30,
    size: ["One Size"],
    sizes: [{ value: "One Size", label: "One Size" }],
    color: "Red",
    materialComposition: "Cotton",
    variant: "With Ear Flaps",
    rating: 4.5,
    reviewsCount: 90,
    boughtInPastMonth: 50,
    newArrival: false,
    deliveryDate: "2025-06-27",
    deliveryCharge: "₹20",
    seller: "Kids Headwear",
    openBoxEligible: false,
    emiStartsAt: 116,
    protectPromiseFee: 5,
    offers: [
      {
        type: "Summer Sale",
        description: "Buy 2 get 1 free",
      },
    ],
  },
  {
    id: 13,
    name: "Kids Socks Pack",
    brand: "HappyFeet",
    category: "Accessories",
    mainImage: "https://th.bing.com/th/id/OIP.mCVT2IKpUYilzWSEHF5HEAHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://th.bing.com/th/id/OIP.mCVT2IKpUYilzWSEHF5HEAHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      "https://th.bing.com/th/id/OIP.VEg6SD2mKRtDJH7gKoaXOgHaIk?w=679&h=786&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      " https://th.bing.com/th/id/OIP.-8y_k-F4TGv7IUIF-siPRgHaH8?w=556&h=597&rs=1&pid=ImgDetMain&cb=idpwebpc2",
    ],
    originalPrice: 299,
    discountedPrice: 209,
    discountPercentage: 30,
    size: ["Small", "Medium", "Large"],
    sizes: [
      { value: "Small", label: "Small" },
      { value: "Medium", label: "Medium" },
      { value: "Large", label: "Large" },
    ],
    color: "Multicolor",
    materialComposition: "Cotton Blend",
    variant: "Pack of 3",
    rating: 4.3,
    reviewsCount: 150,
    boughtInPastMonth: 100,
    newArrival: false,
    deliveryDate: "2025-06-28",
    deliveryCharge: "Free",
    seller: "Footwear Essentials",
    openBoxEligible: true,
    emiStartsAt: 70,
    protectPromiseFee: 5,
    offers: [
      {
        type: "Combo Deal",
        description: "Buy 3 packs get 10% off",
      },
    ],
  },
];

export default KidsproductsData;