
const WomenproductsData = [
  {
    id: 1,
    name: "Floral Print Maxi Dress",
    brand: "ChicStyle",
    category: "Dresses",
    mainImage: "https://n.nordstrommedia.com/id/sr3/739339ae-2dc9-44e8-8bb8-c44cc59d4771.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&dpr=2",
    thumbnailImages: [
      "https://cdnd.lystit.com/520/650/n/photos/e078-2015/04/17/eliza-j-print-petite-womens-floral-print-halter-maxi-dress-product-0-779017145-normal.jpeg",
      "https://n.nordstrommedia.com/id/sr3/e722da90-d5cd-4a4e-9bba-539ce18e6eed.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&dpr=4",
      "https://n.nordstrommedia.com/id/sr3/e722da90-d5cd-4a4e-9bba-539ce18e6eed.jpeg?crop=pad&pad_color=FFF&format=jpeg&w=780&h=1196&dpr=4",
    ],
    originalPrice: 2999,
    discountedPrice: 2099,
    discountPercentage: 30,
    size: ["S", "M", "L", "XL", "XXL"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
      { value: "XXL", label: "XX-Large" },
    ],
    color: "Multi-color",
    materialComposition: "100% Viscose",
    variant: "Floral Blue",
    rating: 4.5,
    reviewsCount: 150,
    boughtInPastMonth: 80,
    newArrival: true,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Fashionista Inc.",
    openBoxEligible: false,
    emiStartsAt: 700,
    protectPromiseFee: 50,
    offers: [
      {
        type: "Bank Offer",
        description: "10% off on ICICI Bank Cards",
      },
      {
        type: "Coupon Code",
        description: "FLAT100 for ₹100 off on first order",
      },
      {
        type: "Special Offer",
        description: "Buy 2 get 10% off",
      },
    ],
  },
  {
    id: 2,
    name: "High-Waist Skinny Jeans",
    brand: "DenimDiva",
    category: "Bottomwear",
    mainImage: "https://th.bing.com/th/id/OIP.8q5jUADY4sj2Wj81iQl3wgHaLH?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://cdn.shopify.com/s/files/1/0293/9277/products/10-26-18_Studio_1_14-31-20_JT34126L_Black_22496_DM.jpg?v=1571439600&width=2400&height=3650&crop=center",
      "https://th.bing.com/th/id/OIP.WnfP2WjAs0qfq8RtzvMMkQHaLH?w=614&h=921&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      "https://cdn.shopify.com/s/files/1/0293/9277/products/10-29-18_Studio_2_13-50-08_P633_DarkDenim0423_JD.jpg?v=1682972892&width=801&height=1202&crop=center",
    ],
    originalPrice: 1899,
    discountedPrice: 1519,
    discountPercentage: 20,
    size: ["26", "28", "30", "32", "34"],
    sizes: [
      { value: "26", label: "Size 26" },
      { value: "28", label: "Size 28" },
      { value: "30", label: "Size 30" },
      { value: "32", label: "Size 32" },
      { value: "34", label: "Size 34" },
    ],
    color: "Dark Blue",
    materialComposition: "98% Cotton, 2% Spandex",
    variant: "Dark Wash",
    rating: 4.2,
    reviewsCount: 210,
    boughtInPastMonth: 120,
    newArrival: false,
    deliveryDate: "2025-06-28",
    deliveryCharge: "₹40",
    seller: "Jeans Galore",
    openBoxEligible: true,
    emiStartsAt: 506,
    protectPromiseFee: 30,
    offers: [
      {
        type: "App Exclusive",
        description: "Extra 5% off on App",
      },
      {
        type: "Seasonal Sale",
        description: "Flat ₹200 off",
      },
    ],
  },
  {
    id: 3,
    name: "Classic White Button-Down Shirt",
    brand: "EleganceWear",
    category: "Tops & Shirts",
    mainImage: "https://th.bing.com/th/id/OIP.FKyd9GeTKtIqE-uSTLE_wwHaLH?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://th.bing.com/th/id/OIP.lxiZeftQEpksSq_RMC_-AAHaLH?w=1000&h=1500&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      "https://th.bing.com/th/id/OIP.lxiZeftQEpksSq_RMC_-AAHaLH?w=1000&h=1500&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      "https://th.bing.com/th/id/OIP.Ad1VYSPb55ip-ANX34-CtgHaLH?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    ],
    originalPrice: 1299,
    discountedPrice: 974,
    discountPercentage: 25,
    size: ["XS", "S", "M", "L", "XL"],
    sizes: [
      { value: "XS", label: "X-Small" },
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
    ],
    color: "White",
    materialComposition: "100% Cotton",
    variant: "Regular Fit",
    rating: 4.6,
    reviewsCount: 95,
    boughtInPastMonth: 60,
    newArrival: false,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Formal Attire",
    openBoxEligible: false,
    emiStartsAt: 325,
    protectPromiseFee: 20,
    offers: [
      {
        type: "Cashback Offer",
        description: "Up to ₹100 cashback on Paytm",
      },
    ],
  },
  {
    id: 4,
    name: "A-Line Midi Skirt",
    brand: "TrendSetter",
    category: "Bottomwear",
    mainImage: "https://cdnd.lystit.com/photos/fc97-2015/08/14/jil-sander-black-midi-a-line-skirt-product-3-793258588-normal.jpeg",
    thumbnailImages: [
      "https://cdna.lystit.com/photos/70c5-2015/08/14/jil-sander-black-midi-a-line-skirt-product-4-793258654-normal.jpeg ",
      " https://cdna.lystit.com/photos/71eb-2015/01/14/givenchy-black-a-line-godet-skirt-product-1-27072404-0-272872096-normal.jpeg",
      " https://cdnc.lystit.com/photos/5630-2015/01/23/givenchy-black-a-line-godet-skirt-product-1-27269623-2-539885359-normal.jpeg",
    ],
    originalPrice: 1599,
    discountedPrice: 1119,
    discountPercentage: 30,
    size: ["S", "M", "L", "XL"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
    ],
    color: "Black",
    materialComposition: "95% Polyester, 5% Spandex",
    variant: "Solid Black",
    rating: 4.3,
    reviewsCount: 70,
    boughtInPastMonth: 45,
    newArrival: true,
    deliveryDate: "2025-06-29",
    deliveryCharge: "Free",
    seller: "Skirts & More",
    openBoxEligible: false,
    emiStartsAt: 373,
    protectPromiseFee: 25,
    offers: [
      {
        type: "Launch Offer",
        description: "Extra 10% off for first 50 customers",
      },
    ],
  },
  {
    id: 5,
    name: "Embroidered Kurta Set",
    brand: "EthnicThreads",
    category: "Ethnic Wear",
    mainImage: "https://i.pinimg.com/originals/3d/ad/13/3dad1341a362b575acc672fdc874f4d7.jpg",
    thumbnailImages: [
      "https://www.omsara.co.uk/wp-content/uploads/C02F2BE9-3812-4BD8-B0EA-4EB3E9F98EF5.jpeg ",
      "https://th.bing.com/th/id/R.d68d0c91a5c0439276773406a0d4005c?rik=%2fFgsuACuwF0VIw&riu=http%3a%2f%2fcdn.shopify.com%2fs%2ffiles%2f1%2f0182%2f1471%2f5470%2fproducts%2fARW-7211_1200x1200.jpg%3fv%3d1610540667&ehk=ly0CChdCxe2mkjE2%2f4Z15BYpuk6yE3LsjarNbUj90Cw%3d&risl=&pid=ImgRaw&r=0 ",
      "https://th.bing.com/th/id/OIP.EU05X10M585agp39PcE4DAHaKL?w=1000&h=1375&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
    ],
    originalPrice: 3499,
    discountedPrice: 2799,
    discountPercentage: 20,
    size: ["S", "M", "L", "XL", "XXL"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
      { value: "XXL", label: "XX-Large" },
    ],
    color: "Maroon",
    materialComposition: "Cotton Blend",
    variant: "With Dupatta",
    rating: 4.7,
    reviewsCount: 180,
    boughtInPastMonth: 90,
    newArrival: false,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Desi Couture",
    openBoxEligible: true,
    emiStartsAt: 933,
    protectPromiseFee: 60,
    offers: [
      {
        type: "Festival Offer",
        description: "Flat ₹500 off",
      },
      {
        type: "Combo Offer",
        description: "Buy 2 Ethnic sets and get 15% off",
      },
    ],
  },
  {
    id: 6,
    name: "Activewear Leggings",
    brand: "FitFlex",
    category: "Activewear",
    mainImage: "https://yogini.bee-logical.co.in/wp-content/uploads/2023/05/High-waist-Leggings-Woman-Leggings-Yoga-Black.png",
    thumbnailImages: [
      " https://fitflex.in/cdn/shop/files/2_ef676f63-be53-448c-a92b-1dcc72d0acf2.jpg?v=1698824543",
      "https://cdna.lystit.com/photos/shopbop/54278620/koral-activewear-BlackScarlet-Tone-Leggings.jpeg ",
      "https://th.bing.com/th/id/OIP.SU1CYMdzF9Ls-3p7miLU4gHaJ4?w=1080&h=1440&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
    ],
    originalPrice: 999,
    discountedPrice: 799,
    discountPercentage: 20,
    size: ["S", "M", "L"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
    ],
    color: "Black",
    materialComposition: "85% Polyester, 15% Spandex",
    variant: "High-Waist",
    rating: 4.4,
    reviewsCount: 110,
    boughtInPastMonth: 75,
    newArrival: true,
    deliveryDate: "2025-06-28",
    deliveryCharge: "Free",
    seller: "Sports Gear",
    openBoxEligible: false,
    emiStartsAt: 266,
    protectPromiseFee: 15,
    offers: [
      {
        type: "Fitness Deal",
        description: "Free shipping on all activewear",
      },
    ],
  },
  {
    id: 7,
    name: "Casual Cropped Top",
    brand: "UrbanChic",
    category: "Tops & Shirts",
    mainImage: "https://cdn-img.prettylittlething.com/1/f/6/e/1f6ef32b4f56aef20f9f1d174fe42839ff392211_cmb4452_1.jpg",
    thumbnailImages: [
      " https://th.bing.com/th/id/OIP.dsoDF-0WExnEnP9FGW_ZOAAAAA?w=474&h=755&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      " https://th.bing.com/th/id/OIP.3LxwVQoCd9ZQKrSBmaRX7QAAAA?w=400&h=638&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      "https://th.bing.com/th/id/OIP.SQj_-FmsZzQmcGlbgJk1AAHaLR?w=800&h=1217&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
    ],
    originalPrice: 799,
    discountedPrice: 559,
    discountPercentage: 30,
    size: ["S", "M", "L"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
    ],
    color: "Pink",
    materialComposition: "60% Cotton, 40% Polyester",
    variant: "Round Neck",
    rating: 4.1,
    reviewsCount: 85,
    boughtInPastMonth: 55,
    newArrival: false,
    deliveryDate: "2025-06-29",
    deliveryCharge: "₹30",
    seller: "Street Style",
    openBoxEligible: false,
    emiStartsAt: 186,
    protectPromiseFee: 10,
    offers: [
      {
        type: "Clearance Sale",
        description: "Up to 50% off",
      },
    ],
  },
  {
    id: 8,
    name: "Comfortable Night Suit Set",
    brand: "DreamWear",
    category: "Sleepwear",
    mainImage: "https://th.bing.com/th/id/OIP.N4W0fr1AGALeJLx6gawfSAAAAA?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://n.nordstrommedia.com/it/32f977d7-3d35-4d94-bbd1-ac0f0194e4e1.jpeg?h=365&w=240&dpr=2 ",
      " https://th.bing.com/th/id/OIP.U6AwyX7clzEw9i6KdruLcAHaLH?w=2821&h=4232&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      " https://i5.walmartimages.com/asr/8bd1a596-86c1-471c-971f-b00f4cdfa50e.c7f7e53dbf506511cea95b611b0073c8.jpeg",
    ],
    originalPrice: 1499,
    discountedPrice: 1049,
    discountPercentage: 30,
    size: ["S", "M", "L", "XL"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
    ],
    color: "Light Blue",
    materialComposition: "Soft Cotton",
    variant: "Pajama Set",
    rating: 4.5,
    reviewsCount: 60,
    boughtInPastMonth: 40,
    newArrival: true,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Cozy Nites",
    openBoxEligible: false,
    emiStartsAt: 350,
    protectPromiseFee: 25,
    offers: [
      {
        type: "Comfort Offer",
        description: "Buy any 2 sleepwear and get 10% off",
      },
    ],
  },
  {
    id: 9,
    name: "Elegant Party Gown",
    brand: "Glamou  rista",
    category: "Dresses",
    mainImage: "https://i.pinimg.com/originals/49/eb/70/49eb70fe82bb950927c4332e3a66371e.jpg",
    thumbnailImages: [
      " https://th.bing.com/th/id/OIP.eZ2NdTS-A1Hi4TTkzQzQgQHaI4?w=600&h=720&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      " https://images-na.ssl-images-amazon.com/images/I/71gb8ucv2qL.jpg",
      "https://i5.walmartimages.com/seo/RYDCOT-Wedding-Guest-Dresses-Women-Summer-2024-Short-Cape-Sleeve-Cocktail-Dress-1950s-Vintage-Elegant-Classy-Swing-Belts-Clearance_5f91805a-868b-475a-a738-62b257a566dd.8013156ea85e8268f69f3efe5eda683b.jpeg ",
    ],
    originalPrice: 5999,
    discountedPrice: 4199,
    discountPercentage: 30,
    size: ["S", "M", "L"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
    ],
    color: "Navy Blue",
    materialComposition: "Net and Satin",
    variant: "Floor Length",
    rating: 4.8,
    reviewsCount: 45,
    boughtInPastMonth: 20,
    newArrival: false,
    deliveryDate: "2025-06-28",
    deliveryCharge: "Free",
    seller: "Red Carpet Fashion",
    openBoxEligible: false,
    emiStartsAt: 1400,
    protectPromiseFee: 100,
    offers: [
      {
        type: "Festive Discount",
        description: "Special discount for limited time",
      },
    ],
  },
  {
    id: 10,
    name: "Printed Palazzo Pants",
    brand: "BohoVibes",
    category: "Bottomwear",
    mainImage: "https://i5.walmartimages.com/asr/e1759457-1186-4b02-8ffd-7e672b28e2a1.e382cc412ad16b0f08c1c68c57efa0c2.jpeg",
    thumbnailImages: [
      "https://i5.walmartimages.com/seo/Taoocy-Women-s-Boho-High-Waist-Flare-Pants-Stretch-Bell-Bottom-Yoga-Pants-Hippie-Flared-Leggings-Pants-Trousers_d3242188-4f60-407e-9d63-eed538292877.cdb072c083542b1beb1614451f6f6e7e.jpeg ",
      " https://i5.walmartimages.com/seo/Musuos-Women-Boho-Flare-Pants-High-Waist-Stretch-Bell-Bottom-Yoga-Pants-Hippie-Leggings_d4487c31-a84b-4235-89e9-6ef696d16497.528b681c3ce97d1a7c8d5e91cb551396.jpeg",
      " https://i5.walmartimages.com/seo/Boho-Flare-Pants-Women-s-High-Waist-Wide-Leg-Trousers-Long-Palazzo-Bell-Bottoms_99894ed4-a22d-467a-a96b-639d87814efd.ea64cb1c62b822507e6848beeadf863e.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF",
    ],
    originalPrice: 1199,
    discountedPrice: 839,
    discountPercentage: 30,
    size: ["S", "M", "L", "XL"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
    ],
    color: "Cream with Prints",
    materialComposition: "Rayon",
    variant: "Wide Leg",
    rating: 4.2,
    reviewsCount: 75,
    boughtInPastMonth: 50,
    newArrival: true,
    deliveryDate: "2025-06-29",
    deliveryCharge: "₹50",
    seller: "Comfort Casuals",
    openBoxEligible: false,
    emiStartsAt: 280,
    protectPromiseFee: 18,
    offers: [
      {
        type: "Summer Sale",
        description: "Flat ₹150 off",
      },
    ],
  },
  {
    id: 11,
    name: "Woolen Cardigan",
    brand: "WarmWoven",
    category: "Winter Wear",
    mainImage: "https://ae01.alicdn.com/kf/HTB1fBFOKXXXXXXqXVXXq6xXFXXXS/Womens-Wool-Coats-European-Style-High-Quality-Autumn-Winter-Jackets-Slim-Woolen-Cardigan-Gray-Jacket-Elegant.jpg",
    thumbnailImages: [
      "https://assets.myntassets.com/h_200,w_200,c_fill,g_auto/h_1440,q_100,w_1080/v1/assets/images/15213216/2022/1/20/81fe8a30-0721-42aa-8257-b5c4689c9efb1642663174854-Duke-Women-Coats-3741642663174341-1.jpg ",
      "https://th.bing.com/th/id/OIP.GX_XEaHTdEuDdLa0Vc4dkgAAAA?rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      "https://target.scene7.com/is/image/Target/GUEST_fb4f8602-685a-46da-8dfe-7a15bb629934 ",
    ],
    originalPrice: 2499,
    discountedPrice: 1749,
    discountPercentage: 30,
    size: ["S", "M", "L", "XL"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
    ],
    color: "Grey",
    materialComposition: "Wool Blend",
    variant: "Open Front",
    rating: 4.5,
    reviewsCount: 55,
    boughtInPastMonth: 30,
    newArrival: false,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Cozy Essentials",
    openBoxEligible: false,
    emiStartsAt: 583,
    protectPromiseFee: 40,
    offers: [
      {
        type: "Winter Special",
        description: "15% off on all sweaters",
      },
    ],
  },
  {
    id: 12,
    name: "Sporty Sweatshirt",
    brand: "Athleisure",
    category: "Activewear",
    mainImage: "https://th.bing.com/th/id/OIP.UMnpw6s0kdM-1bMFcoccpwHaJ3?w=585&h=779&rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://www.stylevore.com/wp-content/uploads/2019/12/0dce95ca90d775f866413048f2a01285.jpg ",
      "https://i.pinimg.com/736x/84/0f/cc/840fcca5e563a50a524b1c9b513f7841.jpg ",
      " https://i.pinimg.com/originals/65/f1/9e/65f19e5ca4af48913f123dfbb8165246.jpg",
    ],
    originalPrice: 1699,
    discountedPrice: 1189,
    discountPercentage: 30,
    size: ["XS", "S", "M", "L"],
    sizes: [
      { value: "XS", label: "X-Small" },
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
    ],
    color: "Navy Blue",
    materialComposition: "Fleece Cotton",
    variant: "Hooded",
    rating: 4.3,
    reviewsCount: 65,
    boughtInPastMonth: 35,
    newArrival: true,
    deliveryDate: "2025-06-28",
    deliveryCharge: "Free",
    seller: "Sporty Style",
    openBoxEligible: false,
    emiStartsAt: 396,
    protectPromiseFee: 28,
    offers: [
      {
        type: "Weekend Offer",
        description: "Buy any activewear top and get 10% off",
      },
    ],
  },
  {
    id: 13,
    name: "Denim Jacket",
    brand: "ClassicJeans",
    category: "Outerwear",
    mainImage: "https://i.pinimg.com/originals/4e/1e/df/4e1edf631c3c941fd134ded44de3795e.jpg",
    thumbnailImages: [
      "https://th.bing.com/th/id/OIP.YBt9GfS_TG3U5W4dyl6YNgHaHa?w=580&h=580&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      " https://i.pinimg.com/736x/81/19/4b/81194b6a974d4f5d5711eb928caf68b4.jpg",
      " https://www.stfrock.com.au/cdn/shop/files/240111_StFrock_Phoebe_AM_BA200-LT-BLU-WK25_0216_1024x1024.jpg?v=1705022412",
    ],
    originalPrice: 2599,
    discountedPrice: 2079,
    discountPercentage: 20,
    size: ["S", "M", "L", "XL"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
    ],
    color: "Light Blue Wash",
    materialComposition: "100% Cotton Denim",
    variant: "Cropped Fit",
    rating: 4.6,
    reviewsCount: 130,
    boughtInPastMonth: 85,
    newArrival: false,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Denim World",
    openBoxEligible: true,
    emiStartsAt: 693,
    protectPromiseFee: 45,
    offers: [
      {
        type: "Fashion Deal",
        description: "Flat ₹250 off on jackets",
      },
    ],
  },
  {
    id: 14,
    name: "Casual T-Shirt Dress",
    brand: "ComfyChic",
    category: "Dresses",
    mainImage: "https://th.bing.com/th/id/OIP.mJsxyS6h9Or8KvfD-y5HYwHaJQ?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      " https://th.bing.com/th/id/OIP._aaYHELA-o8jRK7TBUBWsgHaKX?w=1000&h=1400&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      " https://d2x02matzb08hy.cloudfront.net/img/clothing/hero_image/781230437/200224-1.jpg",
      "https://assets.myntassets.com/h_200,w_200,c_fill,g_auto/h_1440,q_100,w_1080/v1/assets/images/18479244/2022/5/27/3a966728-eea5-471c-b108-3877fe4f23141653667265713NEUDISWomenOliveGreenSolidMidiShirtDress1.jpg ",
    ],
    originalPrice: 1299,
    discountedPrice: 909,
    discountPercentage: 30,
    size: ["S", "M", "L", "XL"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
    ],
    color: "Olive Green",
    materialComposition: "Cotton Jersey",
    variant: "Knee Length",
    rating: 4.4,
    reviewsCount: 90,
    boughtInPastMonth: 65,
    newArrival: true,
    deliveryDate: "2025-06-29",
    deliveryCharge: "Free",
    seller: "Everyday Styles",
    openBoxEligible: false,
    emiStartsAt: 303,
    protectPromiseFee: 20,
    offers: [
      {
        type: "Summer Essential",
        description: "Buy any 2 dresses, get 10% off",
      },
    ],
  },
  {
    id: 15,
    name: "Lace Bralette",
    brand: "SensualSecrets",
    category: "Lingerie",
    mainImage: "https://th.bing.com/th/id/OIP.KFyiWWxLerOLiktSONVBmwHaJ2?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      " https://i.pinimg.com/736x/10/02/cf/1002cfcdd05766a11b4ba7d681cc0dbf.jpg",
      "https://th.bing.com/th/id/R.065faa348ca066fe276d332fb1dc557c?rik=KLlRkVG4Spnlfw&riu=http%3a%2f%2fcdn3.dear-lover.com%2f43786%2f2022%2f05%2f23%2fb%2f6%2fb678b67c9cce993e.jpg&ehk=9xc8byOzS034l%2bNacbPRPyyfcsbaIjK58BI5XDFG91I%3d&risl=&pid=ImgRaw&r=0 ",
      "https://th.bing.com/th/id/OIP.jB5IGi4lxR0K3OeIyBwdowHaHa?w=1024&h=1024&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
    ],
    originalPrice: 899,
    discountedPrice: 629,
    discountPercentage: 30,
    size: ["S", "M", "L"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
    ],
    color: "Black",
    materialComposition: "Lace and Spandex",
    variant: "Non-padded",
    rating: 4.0,
    reviewsCount: 50,
    boughtInPastMonth: 30,
    newArrival: false,
    deliveryDate: "2025-06-28",
    deliveryCharge: "₹40",
    seller: "Intimate Wear",
    openBoxEligible: false,
    emiStartsAt: 210,
    protectPromiseFee: 12,
    offers: [
      {
        type: "Lingerie Offer",
        description: "Buy 3 and get the lowest priced free",
      },
    ],
  },
  {
    id: 16,
    name: "Wide-Leg Jumpsuit",
    brand: "EffortlessFashion",
    category: "Jumpsuits & Rompers",
    mainImage: "https://th.bing.com/th/id/OIP.xc0ie7CnbchJnEhiL7K-SgHaLz?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      "https://cdn-img.prettylittlething.com/6/0/a/6/60a62433b177fc58b2ca4a753701ba53cbf78c06_cng8362_2.jpg?imwidth=2048 ",
      " https://cdn-img.prettylittlething.com/7/f/2/b/7f2ba5304c035fc638897c2017794a0875efa386_cng8362_1.jpg?imwidth=2048",
      " https://media.boohoo.com/i/boohoo/gzz14874_marigold_xl/womens-marigold-petite-sweetheart-ruffle-wide-leg-jumpsuit-/?w=900&qlt=default&fmt.jp2.qlt=70&fmt=auto&sm=fit",
    ],
    originalPrice: 2899,
    discountedPrice: 2029,
    discountPercentage: 30,
    size: ["S", "M", "L", "XL"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
    ],
    color: "Rust",
    materialComposition: "Crepe Polyester",
    variant: "V-Neck",
    rating: 4.5,
    reviewsCount: 70,
    boughtInPastMonth: 40,
    newArrival: true,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "One Piece Wonders",
    openBoxEligible: false,
    emiStartsAt: 676,
    protectPromiseFee: 40,
    offers: [
      {
        type: "Style Steal",
        description: "Flat ₹300 off on jumpsuits",
      },
    ],
  },
  {
    id: 17,
    name: "Pleated Maxi Skirt",
    brand: "FlowyFashions",
    category: "Bottomwear",
    mainImage: "https://i.pinimg.com/originals/91/16/64/9116641f28ded648d6a20399fba65da8.jpg",
    thumbnailImages: [
      "https://i.pinimg.com/originals/91/16/64/9116641f28ded648d6a20399fba65da8.jpg ",
      " https://i.pinimg.com/originals/6c/09/3a/6c093a0412c3c54df383c0470bb9a874.jpg",
      "https://th.bing.com/th/id/OIP.w0zPCQX-8w4LFWrwHR6hfgHaHa?w=800&h=800&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
    ],
    originalPrice: 1799,
    discountedPrice: 1259,
    discountPercentage: 30,
    size: ["S", "M", "L"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
    ],
    color: "Emerald Green",
    materialComposition: "Georgette",
    variant: "Elastic Waist",
    rating: 4.3,
    reviewsCount: 55,
    boughtInPastMonth: 35,
    newArrival: false,
    deliveryDate: "2025-06-29",
    deliveryCharge: "Free",
    seller: "Elegant Drapes",
    openBoxEligible: false,
    emiStartsAt: 420,
    protectPromiseFee: 25,
    offers: [
      {
        type: "Mid-Season Sale",
        description: "Up to 40% off on skirts",
      },
    ],
  },
  {
    id: 18,
    name: "Off-Shoulder Top",
    brand: "GlamGoddess",
    category: "Tops & Shirts",
    mainImage: "https://cdna.lystit.com/photos/f337-2015/12/23/blaque-label-white-off-shoulder-top-white-product-2-067407539-normal.jpeg",
    thumbnailImages: [
      "https://cdna.lystit.com/photos/f337-2015/12/23/blaque-label-white-off-shoulder-top-white-product-2-067407539-normal.jpeg ",
      " https://th.bing.com/th/id/OIP._co5k-21QWr08-Wc2iGpIAHaNI?w=1128&h=2000&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      "https://cdnb.lystit.com/photos/2bb6-2016/02/19/chaser-white-off-shoulder-cotton-peasant-blouse-white-product-2-613387238-normal.jpeg ",
    ],
    originalPrice: 999,
    discountedPrice: 699,
    discountPercentage: 30,
    size: ["S", "M", "L"],
    sizes: [
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
    ],
    color: "White",
    materialComposition: "Cotton Blend",
    variant: "Ruffled",
    rating: 4.1,
    reviewsCount: 60,
    boughtInPastMonth: 40,
    newArrival: true,
    deliveryDate: "2025-06-28",
    deliveryCharge: "₹30",
    seller: "Trendy Tops",
    openBoxEligible: false,
    emiStartsAt: 233,
    protectPromiseFee: 15,
    offers: [
      {
        type: "New Collection",
        description: "Flat ₹100 off on first purchase",
      },
    ],
  },
  {
    id: 19,
    name: "Formal Blazer",
    brand: "PowerDressing",
    category: "Outerwear",
    mainImage: "https://th.bing.com/th/id/OIP.FfALRRAyXPipOcSqbjMxaAHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2",
    thumbnailImages: [
      " https://th.bing.com/th/id/OIP.FfALRRAyXPipOcSqbjMxaAHaHa?rs=1&pid=ImgDetMain&cb=idpwebpc2",
      "https://th.bing.com/th/id/OIP.sHZqO0PJuscQUmvYmA0yegHaHa?w=850&h=850&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
      "https://th.bing.com/th/id/OIP.5TPAe5qkxSAaV_84C-azdQHaLH?w=736&h=1104&rs=1&pid=ImgDetMain&cb=idpwebpc2 ",
    ],
    originalPrice: 3499,
    discountedPrice: 2799,
    discountPercentage: 20,
    size: ["XS", "S", "M", "L", "XL"],
    sizes: [
      { value: "XS", label: "X-Small" },
      { value: "S", label: "Small" },
      { value: "M", label: "Medium" },
      { value: "L", label: "Large" },
      { value: "XL", label: "X-Large" },
    ],
    color: "Black",
    materialComposition: "Polyester Blend",
    variant: "Single Button",
    rating: 4.7,
    reviewsCount: 80,
    boughtInPastMonth: 50,
    newArrival: false,
    deliveryDate: "2025-06-27",
    deliveryCharge: "Free",
    seller: "Corporate Chic",
    openBoxEligible: true,
    emiStartsAt: 933,
    protectPromiseFee: 55,
    offers: [
      {
        type: "Professional Attire",
        description: "Buy a blazer and get 10% off on a formal pant",
      },
    ],
  },
  {
    id: 20,
    name: "Embellished Saree",
    brand: "TraditionalTreasures",
    category: "Ethnic Wear",
    mainImage: "https://i.pinimg.com/originals/ee/36/58/ee3658c7eee66d97961803e076286162.jpg",
    thumbnailImages: [
      " https://i.pinimg.com/originals/ee/36/58/ee3658c7eee66d97961803e076286162.jpg",
      " https://th.bing.com/th/id/OIP.qO9lLFxRpz7j3pbyTaeeQAHaKL?w=800&h=1100&rs=1&pid=ImgDetMain&cb=idpwebpc2",
      " https://cdn.sareeka.com/image/cache/data2022/navy-blue-border-contemporary-style-saree-241391-1000x1375.jpg",
    ],
    originalPrice: 4999,
    discountedPrice: 3499,
    discountPercentage: 30,
    size: ["Free Size"],
    sizes: [{ value: "Free Size", label: "Free Size" }],
    color: "Royal Blue",
    materialComposition: "Silk Blend",
    variant: "With Blouse Piece",
    rating: 4.8,
    reviewsCount: 100,
    boughtInPastMonth: 60,
    newArrival: true,
    deliveryDate: "2025-06-28",
    deliveryCharge: "Free",
    seller: "Indian Attire Hub",
    openBoxEligible: false,
    emiStartsAt: 1166,
    protectPromiseFee: 80,
    offers: [
      {
        type: "Wedding Collection",
        description: "Special discount on bulk orders",
      },
      {
        type: "Exclusive Online",
        description: "Extra ₹200 off for online payment",
      },
    ],
  },
];

export default WomenproductsData;
